sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install 'pip==9.0.1'
  - pip install cython pytest

install:
  - python setup.py build_ext --inplace --with-cython

# commands to run tests
script:
  - PYTHONPATH=. py.test -v tests

notifications:
  email: false

cache:
  pip: true

branches:
  only:
  - master
