language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - pip install 'pip==9.0.1'
  - pip install cython pytest

install:
  - python setup.py build_ext --inplace

# commands to run tests
script:
  - PYTHONPATH=. py.test -v tests

notifications:
  email: false

cache:
  pip: true

branches:
  only:
    - master
